token:
  expiration_time: 86400000
  secret: "{cipher}AYB2+L+5vkff+8jV3nS/L+sYIZ0q5qD1qgaQNaE3jSbasHFiVF6rsMzUpYTUtxrE8Nwcro8dmmMP1SuVYsz9BDEvraw1FPw/KLt8KJdUYbiTG14zeZQSVXPhSVGeNCKsKjoVudCds4JDPp0XjCCtAp8RVtYcpmm766a8IcsQHFhpceHuu0AgQi0xvtAjiN3ABxGRSjMcdQ0+XfcykgJCasy5iBUo4rvCWD5OrVS1zLUqs/K6YqdOu5ScT0ST3NlwPlja8EGPs71jmFyII7GgGVLQA2CauF6KaHSeXYiLISby5dR4WxOYo1mysIIbEsXgHtrHl7ECwZBvb/mbxYhBiJVE2lZSgONsG8mXWHOd0amQRbG9yPiFdc+lrJO9cbmIOhTcx2zCalDmmYJ8Aw3xov1FifuytlYH2IZhop3vsCQbszmVH4N04ulL2mKPfvXQ6ws6SdEhJUNprcwnxRRcJh+0MjLATfPcv1rbw9aeWtSuaFF7PScPW1+40e6X2OdGDrFAEKgrzOZe++JDHwmrfv6r4mkvdo0p+Lz6YO0oSbJQzkC4auOia1jm9KC+UXbdLAA9oAsf/PtcJqUiMqGyAiqBgQPTZiGqHkl/dSxZnsU/VQ=="
gateway:
  ip: 192.168.1.4
